#!/usr/bin/env python3
"""Turn ../../common/data/*.inc into src/data.js.

The tables are NASM `db`/`dd` source, so rather than parse them, assemble them
with nasm and read the bytes back.  A wrapper emits a header of label offsets
first, which is how the slices below are found.  Whatever the assembler makes of
the expressions in the source - `031-2`, the `NT()` macro, `256-70-15` - is what
ends up here, which is the whole point of going through nasm.
"""
import os, re, struct, subprocess, sys, tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.normpath(os.path.join(HERE, '..', '..', '..', 'common', 'data'))
OUT = os.path.normpath(os.path.join(HERE, '..', 'src', 'data.js'))

# The labels the intro reaches into, in the order the wrapper lays them out.
LABELS = ['cubepack', 'chin1', 'chin2', 'fznchar',
          'm_nBytes', 'm_tLfo', 'm_Freq', 'm_dFreq', 'm_Amp', 'm_dAmp', 'm_c', 'm_r',
          'orderList', 'patternList', 'channelList', 'orderStuff', 'theend']

WRAPPER = """\
bits 64
org 0
%s
%%include "cubedata.inc"
%%include "chin_char.inc"
%%include "samples.inc"
%%include "zik.asm"
%%include "orderstuff.inc"
theend:
""" % '\n'.join('    dd %s' % l for l in LABELS)


def assemble():
    with tempfile.TemporaryDirectory() as tmp:
        asm, binf = os.path.join(tmp, 'w.asm'), os.path.join(tmp, 'w.bin')
        open(asm, 'w').write(WRAPPER)
        subprocess.run(['nasm', '-f', 'bin', '-I', DATA + os.sep, asm, '-o', binf],
                       check=True)
        return open(binf, 'rb').read()


def main():
    blob = assemble()
    n = len(LABELS)
    off = dict(zip(LABELS, struct.unpack_from('<%dI' % n, blob, 0)))
    seg = lambda a, b: blob[off[a]:off[b]]

    u8 = lambda b: list(b)
    u16 = lambda b: list(struct.unpack('<%dH' % (len(b) // 2), b))
    f32 = lambda b: list(struct.unpack('<%df' % (len(b) // 4), b))

    # samples.inc is eight parallel arrays; each label is one of them.
    tables = {
        'cubepack':    u8(seg('cubepack', 'chin1')),
        'chin1':       u8(seg('chin1', 'chin2')),
        'chin2':       u8(seg('chin2', 'fznchar')),
        'fznchar':     u8(seg('fznchar', 'm_nBytes')),
        'm_nBytes':    u16(seg('m_nBytes', 'm_tLfo')),
        'm_tLfo':      u8(seg('m_tLfo', 'm_Freq')),
        'm_Freq':      f32(seg('m_Freq', 'm_dFreq')),
        'm_dFreq':     f32(seg('m_dFreq', 'm_Amp')),
        'm_Amp':       f32(seg('m_Amp', 'm_dAmp')),
        'm_dAmp':      f32(seg('m_dAmp', 'm_c')),
        'm_c':         f32(seg('m_c', 'm_r')),
        'm_r':         f32(seg('m_r', 'orderList')),
        'orderList':   u8(seg('orderList', 'patternList')),
        'patternList': u8(seg('patternList', 'channelList')),
        'channelList': u8(seg('channelList', 'orderStuff')),
        'orderStuff':  u8(seg('orderStuff', 'theend')),
    }

    # chin_char.inc has no padding between the glyphs, so the label deltas are
    # the real lengths; assert the ones the drawing code hard-codes.
    assert len(tables['chin1']) == 10 * 2 * 2, len(tables['chin1'])
    assert len(tables['chin2']) == 7 * 2 * 2, len(tables['chin2'])
    assert len(tables['fznchar']) == 3 * 2 * 2, len(tables['fznchar'])
    assert len(tables['cubepack']) == 23
    assert len(tables['m_tLfo']) == 8 and len(tables['m_Freq']) == 8

    def js(v):
        if isinstance(v[0], float):
            # repr round-trips a double; these are float32 values, and the JS
            # side re-rounds with Math.fround, so the text is exact either way.
            return '[' + ', '.join(repr(x) for x in v) + ']'
        return '[' + ', '.join(str(x) for x in v) + ']'

    src = ['// Generated by tools/extract_data.py from ../../common/data - do not edit.',
           '// The intro\'s content, assembled by nasm and read back byte for byte.',
           '']
    for k in ['cubepack', 'chin1', 'chin2', 'fznchar', 'orderList', 'patternList',
              'channelList', 'orderStuff']:
        src.append('export const %s = %s;' % (k, js(tables[k])))
    src.append('')
    src.append('// Instrument parameters (samples.inc).')
    for k in ['m_nBytes', 'm_tLfo', 'm_Freq', 'm_dFreq', 'm_Amp', 'm_dAmp', 'm_c', 'm_r']:
        src.append('export const %s = %s;' % (k, js(tables[k])))
    src.append('')
    open(OUT, 'w').write('\n'.join(src) + '\n')

    print('wrote %s' % OUT)
    for k, v in tables.items():
        print('  %-12s %d' % (k, len(v)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
